intrinio/intrinio-realtime-csharp-sdk

IntrinioRealTimeClient.nuspec, README.md
Removes Crypto references from documentation.
=> Docs: remove crypto references

IntrinioRealtimeMultiExchange/Client.fs, IntrinioRealtimeMultiExchange/Types.fs, IntrinioRealtimeMultiExchange/config.json
=> Add Delayed SIP as a source

IntrinioRealTimeSDK/IntrinioRealTimeClient.nuspec, IntrinioRealTimeSDK/Program.cs, IntrinioRealtimeMultiExchange/CandleStickClient.fs, IntrinioRealtimeMultiExchange/Client.fs, IntrinioRealtimeMultiExchange/IntrinioRealtimeMultiExchange.fsproj, IntrinioRealtimeMultiExchange/Types.fs
=> Add CandlestickClient

IntrinioRealTimeSDK/IntrinioRealTimeClient.nuspec, IntrinioRealTimeSDK/Program.cs, IntrinioRealtimeMultiExchange/Client.fs, IntrinioRealtimeMultiExchange/Config.fs, IntrinioRealtimeMultiExchange/config.json, README.md
=> runtime config

IntrinioRealTimeSDK/IntrinioRealTimeClient.nuspec, IntrinioRealtimeMultiExchange/CandleStickClient.fs, IntrinioRealtimeMultiExchange/Client.fs
CandleClient can specify source delay time.
=> CandleClient can specify source delay time.

IntrinioRealTimeSDK/IntrinioRealTimeClient.nuspec, IntrinioRealTimeSDK/Program.cs, IntrinioRealtimeMultiExchange/CandleStickClient.fs, IntrinioRealtimeMultiExchange/Client.fs, IntrinioRealtimeMultiExchange/Config.fs, IntrinioRealtimeMultiExchange/Types.fs
Intrinio -> Intrinio.Realtime.Equities
=> Namespace Change

IntrinioRealTimeClient.nuspec, IntrinioRealTimeSDK/Program.cs, IntrinioRealtimeMultiExchange/ReplayClient.fs
=> Release v8.1.2

IntrinioRealTimeClient.nuspec, IntrinioRealTimeSDK/Program.cs, IntrinioRealtimeMultiExchange/Client.fs, IntrinioRealtimeMultiExchange/ReplayClient.fs, IntrinioRealtimeMultiExchange/Types.fs
Add more counters for the stats reporting method.
=> Add more counters

IntrinioRealTimeClient.nuspec, IntrinioRealtimeMultiExchange/Client.fs
worker threads get less priority than main thread
=> worker thread gets less priortity

IntrinioRealTimeSDK/IntrinioRealTimeSDK.csproj, IntrinioRealTimeSDK/Program.cs, IntrinioRealTimeSDK/runtimeconfig.template.json, IntrinioRealtimeMultiExchange/CandleStickClient.fs, IntrinioRealtimeMultiExchange/Client.fs, IntrinioRealtimeMultiExchange/IntrinioRealtimeMultiExchange.fsproj, IntrinioRealtimeMultiExchange/ReplayClient.fs, IntrinioRealtimeMultiExchange/Types.fs, IntrinioRealtimeMultiExchange/runtimeconfig.template.json
Added option to filter darkpool events in candleclient.
=> Option to filter darkpool events in candleclient

IntrinioRealTimeClient.nuspec, IntrinioRealtimeMultiExchange/CandleStickClient.fs, IntrinioRealtimeMultiExchange/Client.fs, README.md
-Less dark pool
-Less anomalous trades
=> Improve Anomalous trade filtering

IntrinioRealTimeClient.nuspec, IntrinioRealTimeSDK/IntrinioRealTimeSDK.csproj, IntrinioRealtimeMultiExchange/Client.fs, IntrinioRealtimeMultiExchange/IntrinioRealtimeMultiExchange.fsproj
-Update the auth token every connect
-update from dotnet 6 to 8.
=> Token refresh and project version

Intrinio.Realtime/Options/Tick.cs
Usage of tick constructor for replay.
=> Tick Constructor

Intrinio.Realtime/Equities/Tick.cs, IntrinioRealTimeClient.nuspec
=> Version bump

Intrinio.Realtime/Composite/GreekClient.cs
Allow client to get dividends for securities without a company, like SPY, QQQ, and IWM.
=> Enable Dividend calls for SPY and QQQ, etc

Intrinio.Realtime/Equities/EquitiesWebSocketClient.cs, Intrinio.Realtime/Equities/IEquitiesWebSocketClient.cs, Intrinio.Realtime/Equities/ReplayClient.cs, Intrinio.Realtime/Options/IOptionsWebSocketClient.cs, Intrinio.Realtime/Options/OptionsWebSocketClient.cs, Intrinio.Realtime/WebSocketClient.cs, IntrinioRealTimeClient.nuspec
Add a method to add plugin to interface
=> Add Plugin to Interface

Intrinio.Realtime/Composite/GreekClient.cs, IntrinioRealTimeClient.nuspec
-Fix to allow multiple greek clients
=> Multiple Greek Clients

Intrinio.Realtime/Composite/GreekClient.cs, Intrinio.Realtime/WebSocketClient.cs, IntrinioRealTimeClient.nuspec
Ensure buffer resize is on all websocket creations not just initial
=> Ensure buffer resize is on all websocket creations not just initial

Intrinio.Realtime/WebSocketClient.cs
Allow socket retry backoff times to be configurable
=> configurable backoffs

Intrinio.Realtime/Intrinio.Realtime.csproj, Intrinio.Realtime/WebSocketClient.cs, IntrinioRealTimeClient.nuspec
=> update collections package

Dockerfile, Intrinio.Realtime/Intrinio.Realtime.csproj, Intrinio.Realtime/WebSocketClient.cs, IntrinioRealTimeClient.nuspec, SampleApp/SampleApp.csproj
-Update .NET version from 8 to 9
-Update the Intrinio.Collections package.
=> Release 14.0.0

Intrinio.Realtime/Equities/EquitiesWebSocketClient.cs, Intrinio.Realtime/Equities/Provider.cs, Intrinio.Realtime/Equities/SubProvider.cs, Intrinio.Realtime/Equities/config.json, Intrinio.Realtime/WebSocketClient.cs, IntrinioRealTimeClient.nuspec, README.md, SampleApp/config.json
Add Equities Edge as a provier
=> Equities Edge
